/**
 * Migration Script: Remove memberId from User table
 * This script:
 * 1. Drops the memberId index from User collection
 * 2. Removes memberId field from all users
 * 3. All membership IDs are now managed by Membership table only (CREA2025XXXX format)
 */

require('dotenv').config();
const mongoose = require('mongoose');
const User = require('../models/userModel');

const MONGODB_URI = process.env.MONGO_URI || 'mongodb://localhost:27017/crea';

async function migrate() {
  try {
    console.log('🔌 Connecting to MongoDB...');
    await mongoose.connect(MONGODB_URI);
    console.log('✅ Connected to MongoDB');

    // Drop the memberId index
    console.log('\n🗑️  Dropping memberId index from User collection...');
    try {
      await User.collection.dropIndex('memberId_1');
      console.log('✅ memberId index dropped successfully');
    } catch (error) {
      if (error.code === 27 || error.message.includes('index not found')) {
        console.log('ℹ️  Index already does not exist');
      } else {
        throw error;
      }
    }

    // Remove memberId field from all users
    console.log('\n🧹 Removing memberId field from all users...');
    const result = await User.updateMany(
      { memberId: { $exists: true } },
      { $unset: { memberId: '' } }
    );
    console.log(`✅ Removed memberId from ${result.modifiedCount} users`);

    console.log('\n📊 Migration Summary:');
    console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
    console.log('✓ User table: memberId field removed');
    console.log('✓ Index: memberId_1 dropped');
    console.log('✓ Membership IDs now come from Membership table only');
    console.log('✓ Format: CREA2025XXXX (auto-generated by Membership model)');
    console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n');

    console.log('🎉 Migration completed successfully!\n');
    
  } catch (error) {
    console.error('❌ Migration failed:', error);
    process.exit(1);
  } finally {
    await mongoose.connection.close();
    console.log('🔌 MongoDB connection closed');
  }
}

// Run migration
migrate();
